server:
#  tomcat \u7AEF\u53E3
  port: 8181
#  uri \u7F16\u7801\u683C\u5F0F
  tomcat:
    uri-encoding: utf-8

# \u6570\u636E\u5E93\u8FDE\u63A5\u6C60
spring:
  datasource:
    driver: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: cici
    password: 416518
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5        #初始化连接大小
    minIdle: 5            #最小连接池数量
    maxActive: 20         #最大连接池数量
    maxWait: 60000        #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 1 from dual #测试连接
    testWhileIdle: true          #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false         #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false          #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: true #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxOpenPreparedStatements: 100 #开启poolPreparedStatements后生效
    filters: stat,wall #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProperties属性来打开mergeSql功能;慢SQL记录


  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 300
        max-wait: 100
        max-idle: 16
        min-idle: 8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

mybatis:
  type-aliases-package: com.example.demo.entity     #
  mapper-locations: classpath:/mapper/*.xml

logging:
  config: classpath:logging-config.xml


